version: "3.8"

services:
  postgres:
    image: postgres:latest

    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./gong-jung-backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:password@postgres:5432/mydb
      HOST_IP: ${HOST_IP} # 호스트 IP 전달

    volumes:
      - ./gong-jung-backend/uploads:/app/uploads

  frontend:
    build: ./gong-jung-web

    ports:
      - "80:3001"
    depends_on:
      - backend

volumes:
  pgdata:
